use_frameworks!
platform :ios, '13.0'

target 'TCNClient_Example' do
  pod 'TCNClient', :path => '../'

  target 'TCNClient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['FirebaseFirestoreSwift'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
